language: go
go:
  - 1.8

services:
  - docker
sudo: required

install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get github.com/mattn/goveralls

script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go test -coverprofile=coverage.txt ./mapper
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o sitemapper ./main.go

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci
  - docker build -t tkuhlman/sitemapper .

notifications:
  email:
    - tim@backgroundprocess.com
